
services:
  postgres:
    image: ankane/pgvector:latest
    container_name: pgvector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: municipal_agent
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: